url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/f24-intro-dh" # the subpath of your site, e.g. /blog
title: "Intro to DH" # the name of your site, e.g. ACME Corp.

sass:
  load_paths:
    - _sass
